### PR TITLE
Add Link to plugin Support Pages and move button above fav heart

### PR DESCRIPTION
**Pull request by aaronjorbin**

### CODE REVIEW

**Comment by aaronjorbin** [comment]
If you want me to split these into seperate PRs, I can do it.  I was being lazy.

**Comment by evansolomon** [comment]
Took me a little while to remember how to publish these things.  Bumped the version to 1.2.4 and published in the chrome store. Says it takes up to an hour to update.

**Comment by aaronjorbin** [comment]
Thanks. I appreciate the bump and merge. I also wouldn't be surprised to find out that I'm the only person actively using this.

**Comment by evansolomon** [comment]
If I can keep you happy, it's all worth it.

**Pull request merged**
